[package]
name = "bp_protos"
version = "0.1.0"
edition = "2018"

[dependencies]
prost = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
ulid = { version = "0.5.0", features = ["serde"] }

[build-dependencies]
prost-build = { version = "0.9" }
